(function(){var n=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},r=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a},t=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");
},x=t(this),y=function(a,b){if(b)a:{var e=x;a=a.split(".");for(var g=0;g<a.length-1;g++){var f=a[g];if(!(f in e))break a;e=e[f]}a=a[a.length-1];g=e[a];b=b(g);b!=g&&b!=null&&r(e,a,{configurable:!0,writable:!0,value:b})}},z=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:n(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};
y("Promise",function(a){function b(){this.g=null}function e(c){return c instanceof f?c:new f(function(d){d(c)})}if(a)return a;b.prototype.u=function(c){if(this.g==null){this.g=[];var d=this;this.v(function(){d.M()})}this.g.push(c)};var g=x.setTimeout;b.prototype.v=function(c){g(c,0)};b.prototype.M=function(){for(;this.g&&this.g.length;){var c=this.g;this.g=[];for(var d=0;d<c.length;++d){var h=c[d];c[d]=null;try{h()}catch(k){this.L(k)}}}this.g=null};b.prototype.L=function(c){this.v(function(){throw c;
})};var f=function(c){this.i=0;this.j=void 0;this.h=[];this.F=!1;var d=this.o();try{c(d.resolve,d.reject)}catch(h){d.reject(h)}};f.prototype.o=function(){function c(k){return function(l){h||(h=!0,k.call(d,l))}}var d=this,h=!1;return{resolve:c(this.S),reject:c(this.s)}};f.prototype.S=function(c){if(c===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof f)this.U(c);else{a:switch(typeof c){case "object":var d=c!=null;break a;case "function":d=!0;break a;default:d=!1}d?
this.R(c):this.D(c)}};f.prototype.R=function(c){var d=void 0;try{d=c.then}catch(h){this.s(h);return}typeof d=="function"?this.V(d,c):this.D(c)};f.prototype.s=function(c){this.I(2,c)};f.prototype.D=function(c){this.I(1,c)};f.prototype.I=function(c,d){if(this.i!=0)throw Error("Cannot settle("+c+", "+d+"): Promise already settled in state"+this.i);this.i=c;this.j=d;this.i===2&&this.T();this.N()};f.prototype.T=function(){var c=this;g(function(){if(c.O()){var d=x.console;typeof d!=="undefined"&&d.error(c.j)}},
1)};f.prototype.O=function(){if(this.F)return!1;var c=x.CustomEvent,d=x.Event,h=x.dispatchEvent;if(typeof h==="undefined")return!0;typeof c==="function"?c=new c("unhandledrejection",{cancelable:!0}):typeof d==="function"?c=new d("unhandledrejection",{cancelable:!0}):(c=x.document.createEvent("CustomEvent"),c.initCustomEvent("unhandledrejection",!1,!0,c));c.promise=this;c.reason=this.j;return h(c)};f.prototype.N=function(){if(this.h!=null){for(var c=0;c<this.h.length;++c)q.u(this.h[c]);this.h=null}};
var q=new b;f.prototype.U=function(c){var d=this.o();c.l(d.resolve,d.reject)};f.prototype.V=function(c,d){var h=this.o();try{c.call(d,h.resolve,h.reject)}catch(k){h.reject(k)}};f.prototype.then=function(c,d){function h(m,p){return typeof m=="function"?function(u){try{k(m(u))}catch(v){l(v)}}:p}var k,l,w=new f(function(m,p){k=m;l=p});this.l(h(c,k),h(d,l));return w};f.prototype.catch=function(c){return this.then(void 0,c)};f.prototype.l=function(c,d){function h(){switch(k.i){case 1:c(k.j);break;case 2:d(k.j);
break;default:throw Error("Unexpected state: "+k.i);}}var k=this;this.h==null?q.u(h):this.h.push(h);this.F=!0};f.resolve=e;f.reject=function(c){return new f(function(d,h){h(c)})};f.race=function(c){return new f(function(d,h){for(var k=z(c),l=k.next();!l.done;l=k.next())e(l.value).l(d,h)})};f.all=function(c){var d=z(c),h=d.next();return h.done?e([]):new f(function(k,l){function w(u){return function(v){m[u]=v;p--;p==0&&k(m)}}var m=[],p=0;do m.push(void 0),p++,e(h.value).l(w(m.length-1),l),h=d.next();
while(!h.done)})};return f});y("globalThis",function(a){return a||x});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A=this||self,B=function(a,b){a=a.split(".");var e=A;a[0]in e||typeof e.execScript=="undefined"||e.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)a.length||b===void 0?e=e[g]&&e[g]!==Object.prototype[g]?e[g]:e[g]={}:e[g]=b},C=function(a,b){function e(){}e.prototype=b.prototype;a.Z=b.prototype;a.prototype=new e;a.prototype.constructor=a;a.Y=function(g,f,q){for(var c=Array(arguments.length-2),d=2;d<arguments.length;d++)c[d-2]=arguments[d];return b.prototype[f].apply(g,c)}};function D(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,D);else{var e=Error().stack;e&&(this.stack=e)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}C(D,Error);D.prototype.name="CustomError";function E(a,b){a=a.split("%s");for(var e="",g=a.length-1,f=0;f<g;f++)e+=a[f]+(f<b.length?b[f]:"%s");D.call(this,e+a[g])}C(E,D);E.prototype.name="AssertionError";var F=function(a,b){throw new E("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));};var I=function(a,b){this.J=a===G&&b||"";this.K=H};I.prototype.toString=function(){return this.J};var H={},G={};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var J={};function K(){if(J!==J)throw Error("Bad secret");};var L=globalThis.trustedTypes,M;function N(){var a=null;if(!L)return a;try{var b=function(e){return e};a=L.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(e){throw e;}return a};var O=function(a){K();this.H=a};O.prototype.toString=function(){return this.H+""};var P=function(a){K();this.P=a};P.prototype.toString=function(){return this.P};new P("about:blank");new P("about:invalid#zClosurez");var Q=[],R=function(a){console.warn("A URL with content '"+a+"' was sanitized away.")};Q.indexOf(R)===-1&&Q.push(R);function S(a,b){if(b instanceof O)b=b.H;else throw Error("Unexpected type when unwrapping TrustedResourceUrl");a.src=b;var e;b=a.ownerDocument&&a.ownerDocument.defaultView||window;b=b===void 0?document:b;var g;b=(g=(e="document"in b?b.document:b).querySelector)==null?void 0:g.call(e,"script[nonce]");(e=b==null?"":b.nonce||b.getAttribute("nonce")||"")&&a.setAttribute("nonce",e)};var T=function(a){var b;this.X=b=b===void 0?window:b;a instanceof I&&a.constructor===I&&a.K===H?a=a.J:(F("expected object of type Const, got '"+a+"'"),a="type_error:Const");M===void 0&&(M=N());b=M;this.W=new O(b?b.createScriptURL(a):a);this.A=[];this.B=[];this.G=this.C=!1},U=function(a){a.m.onload=function(){};a.m.onerror=function(){};a.m.onreadystatechange=function(){}},V=function(a){var b=a.X.document,e=b.head||b.documentElement,g=b.createElement("script");a.m=g;g.async=!0;g.defer=!0;S(g,a.W);g.onload=
g.onreadystatechange=function(){g.readyState&&g.readyState!="loaded"&&g.readyState!="complete"||(a.G=!0,U(a),a.A.forEach(function(f){return f()}))};g.onerror=function(){a.C=!0;U(a);a.B.forEach(function(f){return f()})};e.appendChild(g)};T.prototype.load=function(a,b){this.G?a():this.A.push(a);this.C?b():this.B.push(b);this.m||V(this)};function W(a,b){var e=new T(a);B(b,function(g,f){g=g===void 0?function(){}:g;f=f===void 0?function(){}:f;return new Promise(function(q,c){e.load(function(){q();g()},function(){c();f()})})})}W(new I(G,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20241104_00_RC00/cloudshell/cloudshell.js"),"google.devops.tools.loadCloudShell");W(new I(G,"https://www.gstatic.com/devops/connect/releases/devops-learning-tool-library_20241104_00_RC00/walkthrough/walkthrough.js"),"google.devops.tools.loadWalkthrough");}).call(this);
